"""Updated table UserResponse

Revision ID: 92ac6d34990b
Revises: be9c8a5d888b
Create Date: 2025-03-26 12:30:42.357800

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '92ac6d34990b'
down_revision = 'be9c8a5d888b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_responses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=False),
    sa.Column('response_score', sa.Float(), nullable=True),
    sa.Column('response_time', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('transcriptions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcriptions',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('filename', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('text', mysql.TEXT(), nullable=False),
    sa.Column('timestamp', mysql.TIMESTAMP(), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='transcriptions_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('user_responses')
    # ### end Alembic commands ###
